version: '2'
services:
  redis:
    image: redis
    restart: always
    volumes:
      - $HOME/data/redis:/data
    command:  redis-server --appendonly yes

  postgres:
    image: mdillon/postgis:10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=bien
      - POSTGRES_PASSWORD=${BIEN_POSTGRES_PWD}
      - POSTGRES_DB=public_vegbien
      - PG_DATA=/pgdata
    restart: always
    volumes:
      - db_volume:/pgdata

  api:
    build: .
    ports:
      - "8876:8876"
    links:
      - postgres
      - redis

# create volumes if they don't exist already
volumes: 
  db_volume:
